# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://blog.megumifox.com/public/"
#baseurl = "https://blog.megumifox.com/"

# Site title
title = "惠狐之书"

# Copyright
copyright = "© 惠狐之书"

# Language
languageCode = "zh-Hant"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "archie"

# Pagination
paginate = 5

# Enable Disqus integration
disqusShortname = "megumifox"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[permalinks]
    post = "/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    topic = "topics"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    mode="auto" # color-mode → light,dark,toggle or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "一只叫惠的小狐狸的探索故事。"
    mathjax = true # enable MathJax support
    katex = false # enable KaTeX support

    # You can use markdown here.
    brand = "Megumi fox"
    footline = "惠狐之书所有的文章除特别声明外，均使用页脚所指 license。"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Google Analytics.
    googleAnalytics = "G-HM61C25V9Q"

[params.author]
    email = 'i@megumifox.com'
    name = 'Megumifox'

[[params.social]]
    title = "rss"
    icon = "rss" # themify icon : https://themify.me/themify-icons
    url = "/public/index.xml"

[[params.social]]
    title = "github"
    icon = "github" # themify icon : https://themify.me/themify-icons
    url = "https://github.com/MarvelousBlack"

# Main menu Items

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "All posts"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[[menu.main]]
    name = "Topics"
    url = "/topics"
    weight = 2

[[menu.main]]
    name = "Friends"
    url = "/friends"
    weight = 5

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[markupp.goldmark.renderer]
   unsafe = true
